site_name: Vertalo Documentation
docs_dir: .
dev_addr: localhost:1313
use_directory_urls: false
theme:
  name: material
  font: false

markdown_extensions:
  - extra
  - admonition
  - md_in_html
  - mdx_breakless_lists

plugins:
  - same-dir

hooks:
  - scripts/file-list.py
